owner: alvarotorresc
repo: upptime

sites:
  - name: Quedamos
    url: https://quedamos.api.alvarotc.com/health
    icon: https://raw.githubusercontent.com/alvarotorresc/upptime/master/assets/quedamos-icon.svg
    expectedStatusCodes:
      - 200
  - name: alvarotc.com
    url: https://alvarotc.com
    icon: https://alvarotc.com/favicon.svg


status-website:
  cname: status.alvarotc.com
  name: Alvaro TC Status
  theme: dark
  introTitle: "**System Status**"
  introMessage: "Current status of all services. Updated every 5 minutes."
  favicon: https://alvarotc.com/favicon.svg
  navbar:
    - title: Home
      href: https://alvarotc.com
    - title: GitHub
      href: https://github.com/alvarotorresc

notifications:
  - type: telegram
    botKey: $NOTIFICATION_TELEGRAM_BOT_KEY
    chatId: $NOTIFICATION_TELEGRAM_CHAT_ID
