owner: alvarotorresc
repo: upptime

sites:
  - name: Quedamos (Web)
    url: https://quedamos-app-mobile.vercel.app
  - name: Quedamos (API)
    url: https://quedamos.api.alvarotc.com/health
    expectedStatusCodes:
      - 200
  - name: alvarotc.com
    url: https://alvarotc.com


status-website:
  cname: status.alvarotc.com
  name: Alvaro TC Status
  theme: dark
  introTitle: "**System Status**"
  introMessage: "Current status of all services. Updated every 5 minutes."
  favicon: https://alvarotc.com/favicon.svg
  navbar:
    - title: Home
      href: https://alvarotc.com
    - title: GitHub
      href: https://github.com/alvarotorresc

notifications:
  - type: telegram
    botKey: $NOTIFICATION_TELEGRAM_BOT_KEY
    chatId: $NOTIFICATION_TELEGRAM_CHAT_ID
