owner: alvarotorresc
repo: upptime

sites:
  - name: Quedamos API
    url: https://quedamos.api.alvarotc.com/health
    icon: https://quedamos.alvarotc.com/icon-256.png
    expectedStatusCodes:
      - 200
  - name: Quedamos Web
    url: https://quedamos.alvarotc.com
    icon: https://quedamos.alvarotc.com/icon-256.png
    expectedStatusCodes:
      - 200
  - name: alvarotc.com
    url: https://alvarotc.com
    icon: https://alvarotc.com/favicon.svg
    expectedStatusCodes:
      - 200
  - name: Contact form
    url: https://contact.alvarotc.com/health
    icon: https://alvarotc.com/favicon.svg
    expectedStatusCodes:
      - 200
  - name: Cheesy
    url: https://cheesy.alvarotc.com
    icon: https://cheesy.alvarotc.com/favicon.svg
    expectedStatusCodes:
      - 200
  - name: PokeUtils
    url: https://pokeutils.alvarotc.com
    icon: https://pokeutils.alvarotc.com/icons/favicon.svg
    expectedStatusCodes:
      - 200
  - name: DevTools
    url: https://devtools.alvarotc.com
    icon: https://devtools.alvarotc.com/favicon.svg
    expectedStatusCodes:
      - 200
  - name: BaseCero
    url: https://basecero.alvarotc.com
    icon: https://basecero.alvarotc.com/app/icons/icon.svg
    expectedStatusCodes:
      - 200


workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  graphs: "0 0 * * *"
  summary: "0 0 * * *"

status-website:
  cname: status.alvarotc.com
  name: Alvaro TC Status
  theme: dark
  introTitle: "**System Status**"
  introMessage: "Current status of all services made by Alvaro Torres. Checked every 5 minutes."
  favicon: https://raw.githubusercontent.com/alvarotorresc/upptime/master/assets/upptime-icon.svg
  navbar:
    - title: Home
      href: https://status.alvarotc.com
    - title: GitHub
      href: https://github.com/alvarotorresc

notifications:
  - type: telegram
    botKey: $NOTIFICATION_TELEGRAM_BOT_KEY
    chatId: $NOTIFICATION_TELEGRAM_CHAT_ID
